server:
  servlet:
    context-path: /

# 覆盖spring‐boot‐starter‐druid.yaml的项目
spring:
  datasource:
    druid:
      url: jdbc:mysql://43.143.146.155:3306/ICBC?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 178145429
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    druid:
      # 连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
    #SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 100MB
      # 最大支持请求大小
      max-request-size: 30MB

# 覆盖spring‐boot‐mybatis‐plus.yaml的项目

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    id-type: 0
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
  type-aliases-package: com.ten.batch.entity
  mapper-locations: classpath:com/ten/batch/*/mapper/*.xml

jwt:
  config:
    key: icbc-ten
    ttl: 86400000   # 1天

logging:
  config: classpath:log4j2.xml

# 线程池相关 线程池配置
async:
  film-job:
    core-pool-size: 20
    max-pool-size: 100
    keep-alive-seconds: 10
    queue-capacity: 200
    thread-name-prefix: async-Thread-film-service-

  # 读取文件开启线程数量
file:
  thread:
    num: 5


